project:
  type: book
  output-dir: _output

preview:
   - port: 8888
   - browser: false

book:
  title: "Wetenschappelijke Methodiek"
  subtitle: "Richtlijnen en Strategieën voor Goed Onderzoek"
  site-url: https://w-m.pietersmets.be
  date: "24 september 2025"
  author:
    - name: Pieter Smets
      id: ps
      orcid: 0000-0003-0394-0973
      email: mail@pietersmets.be
  abstract: > 
    *Wetenschappelijke Methodiek* is een vak voor de derde graad (doorstroomfinaliteit) dat leerlingen opleidt tot kritische en wetenschappelijk georiënteerde denkers. Het vak combineert inzicht in de wetenschappelijke methode met praktische vaardigheden zoals informatie zoeken, bronnen beheren, correct verwijzen, en helder rapporteren. De klemtoon ligt zowel op *kennis* en *kunde* als op *houding*: nieuwsgierigheid, precisie en zelfreflectie staan centraal.
    In het **vijfde jaar** ligt de nadruk op verkennen en trainen. Leerlingen maken kennis met de fundamenten van metawetenschap, zoals de wetenschappelijke methode, de betrouwbaarheid van bronnen, en de principes van open wetenschap. Daarnaast leren ze doelgericht zoeken naar wetenschappelijke literatuur, beheren ze hun bronnen via Zotero, en oefenen ze academisch schrijven in LaTeX. Het eerste jaar wordt afgesloten met een onderzoeksbrief over een onderwerp binnen elektromagnetisme. Gedurende het hele proces houden leerlingen een portfolio bij waarin ze hun werk, reflecties en groei documenteren.
    In het **zesde jaar** passen leerlingen de verworven vaardigheden zelfstandig toe in een onderzoek naar keuze. Ze starten met het verkennen van mogelijke onderzoeksonderwerpen en schrijven een uitgewerkt onderzoeksvoorstel. Vervolgens voeren ze hun onderzoek uit, waarbij ze systematisch logboek houden van hun voortgang. Het jaar wordt afgesloten met een wetenschappelijke posterpresentatie waarin ze hun bevindingen visueel en mondeling presenteren.
    De volledige leerlijn is cyclisch opgebouwd en stimuleert leerlingen om via feedback, reflectie en herwerking steeds diepgaander te leren. Het einddoel is dat ze niet enkel weten *hoe* wetenschap werkt, maar ook zelf in staat zijn om onderbouwd, helder en kritisch een onderzoeksvraag te benaderen en uit te werken.
  license: "GNU GPLv3"
  chapters:
    - index.qmd
    - intro.qmd
    - part: metawetenschap.qmd
      chapters:
        - wetenschappelijke-methode.qmd
        - bronnen.qmd
        - onderzoek.qmd
#        - statistiek.qmd
        - rapporteren.qmd
        - open-wetenschap.qmd
        - kritisch-denken.qmd
    - part: tools.qmd
      chapters:
        - tool-zoekmachines-en-databanken.qmd
        - tool-ai.qmd
        - tool-referentiebeheer.qmd
        - tool-data-analyse.qmd
        - tool-publicaties.qmd
        - tool-presentaties.qmd
    - part: projects.qmd
      chapters:
        - project5.qmd
        - project6.qmd
    - references.qmd
  cover-image: cover.png
  search: true
  repo-url: https://github.com/psmsmets/WetenschappelijkeMethodiek/
  downloads: [pdf, epub]
  repo-actions: [edit, issue]

lang: nl

bibliography: references.bib

format:
  html:
    number-depth: 3
    theme: 
        light: cosmo
        dark: [cosmo, _assets/theme-dark.scss]
    smooth-scroll: true
    code-overflow: wrap
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/w-m\.pietersmets\.be'
#  pdf:
#    number-depth: 3
#    documentclass: scrreprt
#    cite-method: natbib
#    margin-left: 30mm
#    margin-right: 30mm
#    filters:
#      - first-line-indent

code-tools: false

comment-directive: 
    - "#>"
    - "#?"
    - "//>"
    - "%%>"

execute: 
  echo: false 
  eval: true

embed-resources: false # prevent huge html files!

filters:
  - hide-comment
  - quarto-tikz
  - custom-numbered-blocks # https://github.com/ute/custom-numbered-blocks
  - nameref # https://github.com/shafayetShafee/nameref

latex-auto-install: true

# https://github.com/ute/custom-numbered-blocks
custom-numbered-blocks:
  groups:
    math:
      colors: [948bde, 584eab]
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
    examples:
      colors: [cce7b1, 86b754]
      boxstyle: foldbox.simple
      collapse: false
      listin: [examples]
    opdrachten:
      colors: [e7b1b4, 8c3236]
      boxstyle: foldbox.simple
      collapse: true 
      listin: [portfolio]
#    todos: default  
  classes:
    Theorem:
      label: "Theorema"
      group: math
    Corollary:
      label: "Uitspraak"
      group: math
    Conjecture:
      label: "Stelling"
      group: math
      collapse: true   
    Definition:
      label: "Definitie"
      group: math
      colors: [d999d3, a01793]
    Proof:
      label: "Bewijs"
      group: math
      colors: [d999d3, a01793]
    Exercise:
      label: "Opdracht"
      group: opdrachten 
    Example:
      label: "Voorbeeld"
      group: examples
      collapse: true 
    Feature: 
      group: default
      label: "Methode"
      collapse: false
    Opdracht:
      label: "Opdracht"
      group: opdrachten
    Reflectie:
      group: default
      label: "Reflectie"
      numbered: false
#    TODO:
#      label: "To do"
#      colors: [e7b1b4, 8c3236]
#      group: todos
#      listin: [stilltodo]
#    DONE:
#      label: "Gedaan"
#      colors: [cce7b1, 86b754]  
#      group: todos

nameref:
  section-number: false
