project:
  type: book

book:
  title: "Wetenschappelijke Methodiek"
  subtitle: "Richtlijnen en Strategieën voor Goed Onderzoek"
  # subtitle: "Praktische Richtlijnen en Strategieën voor Goed Onderzoek"
  date: "1 juli 2023"
  author:
    - name: Pieter Smets
      id: ps
      orcid: 0000-0003-0394-0973
      email: mail@pietersmets.be
  abstract: > 
    ... 
  license: "GNU GPLv3"
  chapters:
    - index.qmd
    - intro.qmd
    - part: metawetenschap.qmd
      chapters:
        - wetenschappelijke-methode.qmd
        - bronnen.qmd
        - onderzoek.qmd
        - statistiek.qmd
        - rapporteren.qmd
        - open-wetenschap.qmd
        - kritisch-denken.qmd
    - part: tools.qmd
      chapters:
        - tool-literatuuronderzoek.qmd
        - tool-bibliografie.qmd
        - tool-data-analyse.qmd
        - tool-publicaties.qmd
        - tool-presentaties.qmd
    - part: projects.qmd
      chapters:
        - project-log.qmd
        - project-water.qmd
    - references.qmd
  cover-image: cover.png
  search: true
  repo-url: https://github.com/psmsmets/WetenschappelijkeMethodiek/
  downloads: [pdf, epub]
  repo-actions: [edit, issue]

lang: nl

bibliography: references.bib

format:
  html:
    theme: 
        light: cosmo
        dark: [cosmo, _assets/theme-dark.scss]
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/w-m\.pietersmets\.be'
  pdf:
    documentclass: scrreprt
    cite-method: natbib
#    filters:
#      - first-line-indent

code-tools: false

comment-directive: 
    - "#>"
    - "#?"
    - "//>"
    - "%%>"

execute: 
  echo: false 
  eval: true

embed-resources: true

filters:
  - hide-comment
  - quarto-tikz
#  - nutshell  ## Fix! Geeft icoon in elke header!

latex-auto-install: true
