project:
  type: book
  output-dir: _output

preview:
   - port: 8888
   - browser: false

book:
  title: "Wetenschappelijke Methodiek"
  subtitle: "Richtlijnen en Strategieën voor Goed Onderzoek"
  site-url: https://w-m.pietersmets.be
  date: "3 november 2024"
  author:
    - name: Pieter Smets
      id: ps
      orcid: 0000-0003-0394-0973
      email: mail@pietersmets.be
  abstract: > 
    [deze volgt nog] 
  license: "GNU GPLv3"
  chapters:
    - index.qmd
    - intro.qmd
    - part: metawetenschap.qmd
      chapters:
        - wetenschappelijke-methode.qmd
        - bronnen.qmd
        - onderzoek.qmd
#        - statistiek.qmd
        - rapporteren.qmd
        - open-wetenschap.qmd
        - kritisch-denken.qmd
    - part: tools.qmd
      chapters:
        - tool-literatuuronderzoek.qmd
        - tool-bibliografie.qmd
        - tool-data-analyse.qmd
        - tool-publicaties.qmd
        - tool-presentaties.qmd
    - part: projects.qmd
      chapters:
        - project-intro.qmd
#        - project-log.qmd
#        - project-water.qmd
    - references.qmd
  cover-image: cover.png
  search: true
  repo-url: https://github.com/psmsmets/WetenschappelijkeMethodiek/
  downloads: [pdf, epub]
  repo-actions: [edit, issue]

lang: nl

bibliography: references.bib

format:
  html:
    number-depth: 3
    theme: 
        light: cosmo
        dark: [cosmo, _assets/theme-dark.scss]
    smooth-scroll: true
    code-overflow: wrap
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/w-m\.pietersmets\.be'
#  pdf:
#    number-depth: 3
#    documentclass: scrreprt
#    cite-method: natbib
#    margin-left: 30mm
#    margin-right: 30mm
#    filters:
#      - first-line-indent

code-tools: false

comment-directive: 
    - "#>"
    - "#?"
    - "//>"
    - "%%>"

execute: 
  echo: false 
  eval: true

embed-resources: false # prevent huge html files!

filters:
  - hide-comment
  - quarto-tikz
  - custom-numbered-blocks # https://github.com/ute/custom-numbered-blocks
  - nameref # https://github.com/shafayetShafee/nameref

latex-auto-install: true

# https://github.com/ute/custom-numbered-blocks
custom-numbered-blocks:
  groups:
    math:
      colors: [948bde, 584eab]
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
    examples:
      colors: [cce7b1, 86b754]
      boxstyle: foldbox.simple
      collapse: false
      listin: [examples]
    exercises:
      colors: [e7b1b4, 8c3236]
      boxstyle: foldbox.simple
      collapse: true 
      listin: [exercises]
#    todos: default  
  classes:
    Theorem:
      label: "Theorema"
      group: math
    Corollary:
      label: "Uitspraak"
      group: math
    Conjecture:
      label: "Stelling"
      group: math
      collapse: true   
    Definition:
      label: "Definitie"
      group: math
      colors: [d999d3, a01793]
    Proof:
      label: "Bewijs"
      group: math
      colors: [d999d3, a01793]
    Exercise:
      label: "Opdracht"
      group: exercises
    Example:
      label: "Voorbeeld"
      group: examples
      collapse: true 
    Feature: 
      group: default
      label: "Methode"
      collapse: false
#    TODO:
#      label: "To do"
#      colors: [e7b1b4, 8c3236]
#      group: todos
#      listin: [stilltodo]
#    DONE:
#      label: "Gedaan"
#      colors: [cce7b1, 86b754]  
#      group: todos

nameref:
  section-number: false
