# Deel 2 - Hulpmiddelen

Dit deel biedt je verschillende *tools* of hulpmiddelen aan om je ondersteunen bij je onderzoek. 
De voorkeur gaat telkens naar *vrije software* om zo min mogelijk afhankelijk te zijn. [^1]
Er bestaan veel *gratis* tools, welke vaak *closed source software* zijn van bedrijven. 
Gratis software bestaat in essentie niet. 
Jij en/of jouw data zijn dan het product. 
Daarbij kan software van bedrijven plots veranderen, stoppen of kan het bedrijf overgenomen worden, wat nefast kan zijn voor jouw (data).

Alle toegelichte hulpmiddelen in dit boek zijn daarom vrije software. 
Je kan elke tool lokaal installeren en beheren, zonder enige kosten. 
Zolang het besturingssysteem de software ondersteunt blijft de tool ook werken.
Enige computerervaring is af en toe wel vereist. 

:::{.callout-tip title="Vrije software"}
Vrije software is een verzamelnaam van computersoftware die wordt vrijgegeven onder een licentie waarin de houder van het auteursrecht gebruikers het recht geeft om de software en de broncode ervan te gebruiken, te bestuderen, te wijzigen en te verspreiden aan iedereen en voor elk doel.
Deze vier vrijheden worden in de talloze vrijesoftwarelicenties in min of meer grote variaties en nuances beschreven. De essentie van al deze licenties en de reden waarom ze tot de groep van de vrije software behoren, is dat de makers van de software hun gebruikers stimuleren om de software te helpen verbeteren en uit te breiden. 
:::

[^1]: <https://nl.wikipedia.org/wiki/Portaal:Vrije_software>
